### ISSUE TITLE
Create JSON or YAML file with plugin names and SHA

### ISSUE THREAD

**Issue by maximilien** [knative-sandbox/homebrew-kn-plugins#16]
This repo contains formulas for all _supported_ `kn` plugins by the Knative community.

Other tooling might need such a list, this issue / proposal is to create a YAML or JSON file that would contain the list of plugins names, repos, and latest version SHAs and have the formulas use this file, instead of embedding into code. 

The side effect would be that such a list would be generally useful for other tools, e.g., the VSCode plugin by @joshuawilson or documentation generation for the list of “approved plugins”.

Here is one proposal for this file:

```yaml
---
- source-kafka:
    - 0.21.0:
        - sha: 9a10e1b0ff9a035d88b6d69d5d7bf235de8a2b4b1002062688e104fe936f4161
        - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka
- admin:
    - 0.21.0:
        - sha: 62009d94134abb23f208b725ba47eb5da5ca8bf55a554300576cbc595f111069
        - repo: https://github.com/knative-sandbox/kn-plugin-admin 
```

Including a `repo` field to allow for plugins that would be located outside of `knative-sandbox` since otherwise I would have to assume that’s where it’s coming from. 

We could call it `plugins.yaml` and add new versions entries for each plugin with a new release and new top level entries for additional plugins as we vet them.

WDYT Josh? Could you use this?

CC: @rhuss @navidshaikh

**Comment by joshuawilson** [comment]
This idea is fantastic. We could use it to control the list of all the plugins. 

Is it auto-generated? 

For this to be useful in an automated process, the repo would need to point the download link and the sha for Windows, Mac, and Linux.

**Comment by maximilien** [comment]
Agree @joshuawilson automated would be great but we don't yet have a means to decide which plugin gets into next release or even test them. Until we do this is manual. But once we have more of the decisions or process automated I can see one output being this file. For now, let's have it manual. I'll wait a day before pushing some code to allow others to chime in.

**Comment by joshuawilson** [comment]
Manual is fine, I was just curious. A curated list is good as we know what is in it.

It will need the repo and sha for Win, Mac, and Linux. 
It will need to the repo like to be the actual download URL.

**Comment by maximilien** [comment]
OK what about something like this:

```yaml
---
- source-kafka:
    - 0.21.0:
        - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka
        - sha:
          - darwin-amd64: 9a410c2062a351f778fcf84a85909d50a886dfc5daeb5554a16b03db201ee83c
          - linux-amd64: 650136bb614910c38aa3c0e12321bba2fda1df321746ad4a1f53f3f5d2229096
          - linux-arm64: 8c76ea635fc06919dd15657dc8565db15f97d2dbe7d30302eab5f9d54e73f26c
          - windows-amd64.exe: 0ae2686d47e95ccb0c3177af5f6d9f8368bc2d17a72d96ba033300a34881f836
          - linux-s390x: f30ff3127b2a9e91f9a943589eb778590a4528be93720eecf9cf67aebb778e33
          - linux-ppc64le: dbbf4794694c8e9d6967f72e189200b64a1ede09bebfd7e7a426570d91f9230e
- admin:
    - 0.21.0:
        - repo: https://github.com/knative-sandbox/kn-plugin-admin
        - sha:
          - darwin-amd64: d1232dffcfaca518b77f54b6ce49b478b1e9409203acb9ea4a1cfe38194f5576
          - linux-amd64: 863ea33842f6ec32eaa6818f45554e1cb997731a52248d659c687c9d2ff00f23
          - linux-arm64: f14d417cc7a25be3ca220954fbfc5cab9e8f0a724b1796b6272e097c1dbe5a2e
          - windows-amd64.exe: 2d9be90517987157d7951c857207160c91d50cd30cf6413279b6fc594bd48994
          - linux-s390x: e9ffe88414745b677eccc79f16717957b838e340dbe75419c5f5fbf481cf66af
          - linux-ppc64le: 30db7f3df267c1943e1a0174d0f97f77fb97ee008b37cc93f565e6035dc1f3a2
```

And yes it will be `plugins.yml` on this repo.

**Comment by joshuawilson** [comment]
We need a way to navigate to the download link.

The actual download for the mac source-kafka is: 
`https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/download/v0.22.0/kn-source-kafka-darwin-amd64`

This is a lot different from `https://github.com/knative-sandbox/kn-plugin-source-kafka`. If we only have this link, then we need to build the rest based on information in this yaml file.

**Comment by joshuawilson** [comment]
What about something like this?

```
- source-kafka:
    - 0.21.0:
        - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka
        - darwin-amd64: 
            - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/download/v0.22.0/kn-source-kafka-darwin-amd64
            - sha: 9a410c2062a351f778fcf84a85909d50a886dfc5daeb5554a16b03db201ee83c
        - linux-amd64: 
            - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/download/v0.22.0/kn-source-kafka-linux-amd64
            - sha: 650136bb614910c38aa3c0e12321bba2fda1df321746ad4a1f53f3f5d2229096
        - linux-arm64: 
            - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/download/v0.22.0/kn-source-kafka-linux-arm64
            - sha: 8c76ea635fc06919dd15657dc8565db15f97d2dbe7d30302eab5f9d54e73f26c
```

Though I'm not sure why there are 2 `kn-source-kafka-linux-amd64` with different hashes.

**Comment by maximilien** [comment]
Actually, what about this:

```yaml
---
source-kafka:
  0.21.0:
    repo: https://github.com/knative-sandbox/kn-plugin-source-kafka
    shas:
      darwin-amd64: 9a410c2062a351f778fcf84a85909d50a886dfc5daeb5554a16b03db201ee83c
      linux-amd64: 650136bb614910c38aa3c0e12321bba2fda1df321746ad4a1f53f3f5d2229096
      linux-arm64: 8c76ea635fc06919dd15657dc8565db15f97d2dbe7d30302eab5f9d54e73f26c
      windows-amd64.exe: 0ae2686d47e95ccb0c3177af5f6d9f8368bc2d17a72d96ba033300a34881f836
      linux-s390x: f30ff3127b2a9e91f9a943589eb778590a4528be93720eecf9cf67aebb778e33
      linux-ppc64le: dbbf4794694c8e9d6967f72e189200b64a1ede09bebfd7e7a426570d91f9230e
admin:
  0.21.0:
      repo: https://github.com/knative-sandbox/kn-plugin-admin
      shas:
        darwin-amd64: d1232dffcfaca518b77f54b6ce49b478b1e9409203acb9ea4a1cfe38194f5576
        linux-amd64: 863ea33842f6ec32eaa6818f45554e1cb997731a52248d659c687c9d2ff00f23
        linux-arm64: f14d417cc7a25be3ca220954fbfc5cab9e8f0a724b1796b6272e097c1dbe5a2e
        windows-amd64.exe: 2d9be90517987157d7951c857207160c91d50cd30cf6413279b6fc594bd48994
        linux-s390x: e9ffe88414745b677eccc79f16717957b838e340dbe75419c5f5fbf481cf66af
        linux-ppc64le: 30db7f3df267c1943e1a0174d0f97f77fb97ee008b37cc93f565e6035dc1f3a2
```

Also one of the linux SHA is for `amd64` and one is for `arm64` <-- not the same.

**Comment by joshuawilson** [comment]
Why did you edit my example? I was just a suggestion.

**Comment by maximilien** [comment]
Yeah. Sorry. See mine. OK for you?

**Comment by joshuawilson** [comment]
Without the download link how do we get the plugin?

**Comment by joshuawilson** [comment]
I'll try my example again.

```
source-kafka:
  0.22.0:
    darwin-amd64: 
      - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/download/v0.22.0/kn-source-kafka-darwin-amd64
      - sha: 9a410c2062a351f778fcf84a85909d50a886dfc5daeb5554a16b03db201ee83c
    linux-amd64: 
      - repo: https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/download/v0.22.0/kn-source-kafka-linux-amd64
      - sha: 650136bb614910c38aa3c0e12321bba2fda1df321746ad4a1f53f3f5d2229096
```

This is only a partial example to show how to include the download link.
